A22-5G:
  kernel:
    - git clone https://github.com/Dan13254/android_kernel_samsung_a226b.git -b master
  clang:
    - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main
  config:
    - make O=out ARCH=arm64 a22x_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out
  target:
    - out/arch/arm64/boot/Image.gz-dtb
  anykernel:
    - a22
  kernelSU:
    - stable-pin

Clean:
  out:
    - rm -rf out
  kernel:
    - make mrproper
  custom:
    - git status

KernelSU:
  version:
    stable-pin:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s kernelsu-version
